defaultsDeep handle undefined
a-synchronous/rubico pull request #186
Opened 2021-06-27 09:42 UTC by FredericHeem

2021-06-27 11:19 UTC, richytong commented
Hello, I believe the value == null check also accounts for undefined

2021-06-27 21:32 UTC, richytong commented
Also looks like optional chaining isn't supported in node 12

https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12

2021-06-28 23:05 UTC, richytong requested changes

2021-06-28 23:05 UTC, richytong commented on x/defaultsDeep.js
> +    } else if (item.constructor == Object && defaultItem && defaultItem.constructor == Object) {
could we make the defaultItem part of this check defaultItem != null?

2021-06-28 23:05 UTC, richytong commented on x/defaultsDeep.js
> +  if (value.constructor == Object && defaultCollection && defaultCollection.constructor == Object) {
same thing with defaultCollection, could we make it defaultCollection != null?

2021-06-28 23:09 UTC, richytong requested changes
It looks like if the default object is null we should just return the argument like the identity function so that check should go in the top level defaultsDeep. Could you change the pr so that it checks for it there?

2021-06-28 23:10 UTC, richytong commented
I think we can do the check even before we return the function defaulting. If the default value is null return identity instead of defaulting.

2021-06-29 15:45 UTC, FredericHeem commented on x/defaultsDeep.js
> +  if (value.constructor == Object && defaultCollection && defaultCollection.constructor == Object) {
done

2021-06-29 16:44 UTC, richytong approved these changes
LGTM

2021-06-29 16:45 UTC, merged