New examples
a-synchronous/rubico pull request #210
Opened 2022-04-03 14:26 UTC by lulldev

#177

2022-04-04 01:04 UTC, richytong requested changes
If the example is designed to run in the browser let's just use ESM over any bundlers

2022-04-04 01:04 UTC, richytong commented on examples/type-to-search-wiki/src/app.js
> +  resultList.innerHTML = reduce((html, item) => html + template.replace(/\{name\}/g, item), '')(resultContent)
i would avoid using a rubico function when the array property function would read more naturally here

```
result.innerHTML = resultContent.reduce...
```

2022-04-12 19:06 UTC, richytong commented
by the way @lulldev you aren't showing up in the contributors list most likely because your email isn't added to your github account. You should add the one associated with this commit https://github.com/a-synchronous/rubico/commit/ff1ec6167947268f9f5a6540c64d068f77bbcde3.patch

2022-04-13 20:39 UTC, lulldev commented
@richytong about esm. can be more?

2022-04-13 20:42 UTC, richytong requested changes
moving everything to ESM means we should replace all the requires with import statements, as well as all the module.exports statements with export default. We should also rename the `src` folder to `public`. In order to import rubico in the browser I recommend importing the core globally by adding this script to the head of the index.html

```html
<script defer src="https://unpkg.com/rubico@1.6.17/dist/rubico.min.js" crossorigin></script>
```

2022-04-13 22:20 UTC, richytong requested changes
also with ESM we don't need a build step anymore. All we have to do is serve the `public` folder with a static file server like [serve](https://www.npmjs.com/package/serve)

2022-04-13 22:24 UTC, richytong commented
also about your email I think you should look into making the one in your commits match up to your actual email. This is done through creating a new gpg key and adding it to your github gpg keys. This is a pretty good guide for it https://docs.github.com/en/enterprise-server@3.1/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

2022-04-14 19:04 UTC, richytong approved these changes
all right, if you wanna keep src that's fine. I also ran your example, everything looks good.

LGTM

2022-04-14 19:05 UTC, merged